// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSGeDTBydzcTXjzUQJN3p7AB8c_zfPcms',
    appId: '1:1045680177635:web:6fc695bcddb847ebe060d6',
    messagingSenderId: '1045680177635',
    projectId: 'lenpay-f7835',
    authDomain: 'lenpay-f7835.firebaseapp.com',
    storageBucket: 'lenpay-f7835.firebasestorage.app',
    measurementId: 'G-8RB1QSW4S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKB0tF4rxDy977PoPpbfGcFBYyHvcfGFg',
    appId: '1:1045680177635:android:3247f849a0addd57e060d6',
    messagingSenderId: '1045680177635',
    projectId: 'lenpay-f7835',
    storageBucket: 'lenpay-f7835.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5N79wyO9YF_s9tzCHkmiebYyyBNa5DaA',
    appId: '1:1045680177635:ios:29d9747288ea5f03e060d6',
    messagingSenderId: '1045680177635',
    projectId: 'lenpay-f7835',
    storageBucket: 'lenpay-f7835.firebasestorage.app',
    iosBundleId: 'com.example.lenpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5N79wyO9YF_s9tzCHkmiebYyyBNa5DaA',
    appId: '1:1045680177635:ios:29d9747288ea5f03e060d6',
    messagingSenderId: '1045680177635',
    projectId: 'lenpay-f7835',
    storageBucket: 'lenpay-f7835.firebasestorage.app',
    iosBundleId: 'com.example.lenpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSGeDTBydzcTXjzUQJN3p7AB8c_zfPcms',
    appId: '1:1045680177635:web:1818044e5536eb35e060d6',
    messagingSenderId: '1045680177635',
    projectId: 'lenpay-f7835',
    authDomain: 'lenpay-f7835.firebaseapp.com',
    storageBucket: 'lenpay-f7835.firebasestorage.app',
    measurementId: 'G-W3K14L4Q0J',
  );

}